# Generated by Django 4.2.2 on 2023-06-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_persona_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('canciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
