# Generated by Django 4.2.2 on 2023-07-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_dj_pista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Invitado',
        ),
    ]
