# Generated by Django 4.2.2 on 2023-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_persona_invitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pista',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
