# Generated by Django 4.2.2 on 2023-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_dj_descripcion_invitado_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='fecha_de_presentacion',
            field=models.DateField(null=True),
        ),
    ]
