# Generated by Django 4.2.2 on 2023-07-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_dj_fecha_de_presentacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pista',
        ),
    ]
