# Generated by Django 4.2.2 on 2023-08-08 01:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_delete_pista'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='imagen_dj',
            field=models.ImageField(blank=True, null=True, upload_to='img_djs'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='imagen_invitado',
            field=models.ImageField(blank=True, null=True, upload_to='img_invitados'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
