# Generated by Django 4.2.2 on 2023-07-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('contenido', models.TextField(null=True)),
                ('autor', models.CharField(max_length=20)),
                ('fecha_de_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoResenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img_resenias')),
                ('resenia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.resenia')),
            ],
        ),
    ]
