# Generated by Django 4.2.2 on 2023-07-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_resenia_foto_resenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='cumpleanios',
            field=models.DateField(null=True),
        ),
    ]
