# Generated by Django 4.2.2 on 2023-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_infousuario_cumpleanios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infousuario',
            name='cumpleanios',
        ),
        migrations.AddField(
            model_name='infousuario',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
