# Generated by Django 4.2.2 on 2023-08-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_infousuario_cumpleanios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoResenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_resenia', models.ImageField(blank=True, null=True, upload_to='resenia_img')),
                ('resenia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.resenia')),
            ],
        ),
    ]
