# Generated by Django 4.2.2 on 2023-08-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_inforesenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenResenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img_resenias')),
            ],
        ),
        migrations.AddField(
            model_name='resenia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_resenias/'),
        ),
        migrations.DeleteModel(
            name='InfoResenia',
        ),
    ]
