# Generated by Django 4.2.2 on 2023-08-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_imagenresenia_resenia_imagen_delete_inforesenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenResenia',
        ),
    ]
