# Generated by Django 4.2.2 on 2023-08-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_delete_imagenresenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenia',
            name='imagen',
        ),
    ]
