# Generated by Django 4.2.2 on 2023-08-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_infousuario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infousuario',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='infousuario',
            name='cumpleanios',
            field=models.DateField(blank=True, null=True),
        ),
    ]
