# Generated by Django 4.2.2 on 2023-08-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_remove_infousuario_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infousuario',
            name='cumpleanios',
        ),
    ]
